version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: /app/ctf.py
  
  ftp:
    container_name: ftp-server
    image: garethflowers/ftp-server
    environment:
      - FTP_USER=${FTP_USERNAME}
      - FTP_PASS=${FTP_PASSWORD}
    restart: always
    ports:
      - '20-21:20-21'
    volumes:
      - ./shared:/home/${FTP_USERNAME}/shared

